---
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: develop 
  password: develop 
  database: squash_development
test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: test
  password: test
  database: squash_test
